// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import IceCreamChartController from "./ice_cream_chart_controller"
application.register("ice-cream-chart", IceCreamChartController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
