services:
  - type: web
    name: icetagram-app2
    env: ruby
    region: singapore
    plan: free
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: icetagram-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false